import { usePrintSettings } from '../../hooks/useSelectiveState';
import React from 'react';
import { useAuth } from '../../context/AuthContext';

export interface ReportFooterProps {
    /** Override signed-in user name for the "Generated by" line */
    generatedBy?: string;
}

const ReportFooter: React.FC<ReportFooterProps> = ({ generatedBy: generatedByProp }) => {
    const printSettings = usePrintSettings();
    const { user } = useAuth();
    const generatedBy = generatedByProp ?? user?.name;

    if (!printSettings) return null;

    return (
        <div className="report-branding-footer mt-8 pt-4 border-t border-app-border text-center text-xs text-app-muted">
             {printSettings.footerText && <p className="font-medium mb-1">{printSettings.footerText}</p>}
             {generatedBy && <p className="mb-1">Generated by: {generatedBy}</p>}
             {printSettings.showDatePrinted && <p>Printed on: {new Date().toLocaleString()}</p>}
        </div>
    );
};

export default ReportFooter;