import { tc, uatId, withIds } from './helpers.mjs';

const NAV_PM = 'Sidebar → Construction → PM cycle';
const NAV_BUDGET = 'Sidebar → Financials → Budget Planner';
const NAV_PERSONAL = 'Sidebar → Financials → Personal transactions';

export const CHAPTER_09 = {
  number: 9,
  title: 'PM Cycle',
  idRange: 'UAT-451 – UAT-480',
  purpose: 'Verify Project Management fee cycle: project PM configuration, cycle allocation, fee ledger, payouts, and expense base calculations.',
  businessFlow: `Select Project → Configure PM % → Run Cycle Allocation → Fee Ledger → Record Payout`,
  requiredTestData: [
    'Project: Sunrise Towers with construction expenses',
    'PM fee percentage: e.g. 5%',
    'Excluded cost categories configured',
  ],
  dependencies: ['Chapter 5 — project expenses/bills posted', 'real_estate license + financial write'],
  expectedOutputs: [
    'PM cycle allocation run creates fee bills',
    'Fee ledger shows allocated/paid/balance',
    'Payout recorded against allocation',
  ],
  checklist: [
    'Project selected in PM cycle',
    'PM config saved',
    'Cycle allocation executed',
    'Fee ledger balanced',
    'Payout recorded',
  ],
  cases: withIds(451, [
    tc(uatId(451), 'PM Cycle', 'Open PM cycle', 'Navigate to PM cycle module', NAV_PM, 'real_estate + financial write', 'None', ['Sidebar → Construction → PM cycle.'], 'Project PM Manager screen loads.'),
    tc(uatId(452), 'PM Cycle', 'Select project', 'Select project for PM management', `${NAV_PM} → Select Project`, 'Project Sunrise Towers with expenses', 'Project: Sunrise Towers', ['Use Select Project picker.', 'Choose Sunrise Towers.'], 'Project context loaded; stats panel visible.'),
    tc(uatId(453), 'PM Cycle', 'Configure PM fee', 'Open PM configuration', `${NAV_PM} → Configure`, 'Project selected', 'PM fee %: 5\nCycle: Monthly', ['Click Configure button.', 'Set PM fee percentage and cycle frequency.', 'Save.'], 'PM configuration saved on project.'),
    tc(uatId(454), 'PM Cycle', 'View expense stats', 'Review Total Expense and Net Cost Base', NAV_PM, 'Project with posted bills from Ch.5', 'None', ['Review stats: Total Expense, Excluded Cost, Net Cost Base, Balance Due.'], 'Expense stats reflect project posted expenses minus exclusions.'),
    tc(uatId(455), 'PM Cycle', 'Excluded cost categories', 'Configure excluded categories in PM config', `${NAV_PM} → Configure → exclusions`, 'PM config open', 'Exclude: Land cost category if present', ['Mark categories excluded from PM fee base.', 'Save.'], 'Excluded Cost stat updates on recalculation.'),
    tc(uatId(456), 'PM Cycle', 'Run Cycle Allocation', 'Execute cycle allocation', `${NAV_PM} → Run Cycle Allocation`, 'PM config saved; expenses exist', 'Cycle: current month', ['Click Run Cycle Allocation.', 'Confirm Refresh Cycle Allocation modal if shown.', 'Wait for completion.'], 'PM fee bills/allocation rows created; Fee Ledger populated.'),
    tc(uatId(457), 'PM Cycle', 'Fee Ledger — view', 'Review Fee Ledger table', `${NAV_PM} → Fee Ledger`, 'Allocation UAT-456', 'None', ['Review Fee Ledger columns: Type, Cycle/Ref, Date, Allocated, Paid, Balance, Action.'], 'Ledger rows show allocation entries with balances.'),
    tc(uatId(458), 'PM Cycle', 'Fee Ledger — allocated amount', 'Verify allocated PM fee amount', `${NAV_PM} → Fee Ledger`, '5% PM on net cost base', 'Expected: 5% of Net Cost Base', ['Calculate expected fee manually.', 'Compare to Allocated column.'], 'Allocated amount matches PM % × Net Cost Base.'),
    tc(uatId(459), 'PM Cycle', 'Record Payout', 'Record PM fee payout', `${NAV_PM} → Record Payout`, 'Outstanding allocation balance', 'Account: HBL Current Account\nAmount: allocation balance', ['Click Record Payout on ledger row.', 'Enter payment details.', 'Confirm.'], 'Paid column updated; Balance Due reduced.'),
    tc(uatId(460), 'PM Cycle', 'Balance Due zero', 'Verify Balance Due after full payout', NAV_PM, 'Full payout UAT-459', 'None', ['Review Balance Due stat after payout.'], 'Balance Due approaches zero when fully paid.'),
    tc(uatId(461), 'PM Cycle', 'Re-run allocation', 'Refresh cycle allocation', `${NAV_PM} → Run Cycle Allocation (again)`, 'Prior allocation exists', 'Same cycle period', ['Run allocation again for same cycle.', 'Confirm refresh/replace behavior in modal.'], 'Allocation refreshed per system rules; no duplicate orphan bills.'),
    tc(uatId(462), 'PM Cycle', 'Delete allocation', 'Delete PM cycle allocation if supported', `${NAV_PM} → Fee Ledger → Delete/Action`, 'Test allocation row', 'None', ['Use delete/recalculate action on allocation if available.'], 'Allocation removed or recalculated per UI action.'),
    tc(uatId(463), 'PM Cycle', 'Weekly cycle', 'Configure weekly PM cycle', `${NAV_PM} → Configure`, 'PM config', 'Cycle: Weekly', ['Change cycle frequency to Weekly.', 'Save.', 'Run allocation.'], 'Weekly cycle ID appears in ledger.'),
    tc(uatId(464), 'PM Cycle', 'Yearly cycle', 'Configure yearly PM cycle', `${NAV_PM} → Configure`, 'PM config', 'Cycle: Yearly', ['Change to Yearly cycle.', 'Save.'], 'Yearly cycle configuration saved.'),
    tc(uatId(465), 'PM Cycle', 'Monthly cycle default', 'Revert to monthly cycle', `${NAV_PM} → Configure`, 'None', 'Cycle: Monthly', ['Set cycle back to Monthly.', 'Save.'], 'Monthly cycle restored.'),
    tc(uatId(466), 'Construction', 'PM Fee Log cross-check', 'Cross-check PM Fee Log report', 'Project construction → Payouts → PM Fee Log', 'PM payout UAT-459', 'None', ['Open PM Fee Log under Project construction.', 'Compare to PM cycle ledger.'], 'PM Fee Log entries consistent with PM cycle payouts.'),
    tc(uatId(467), 'Construction', 'PM Cost Report', 'Run PM Cost Report', 'Project construction → Reports → PM Cost Report', 'PM allocations exist', 'Project: Sunrise Towers', ['Run PM Cost Report.'], 'PM costs summarized in construction reports.'),
    tc(uatId(468), 'PM Cycle', 'Expense distribution screen', 'Verify no standalone expense distribution UI', NAV_PM, 'None', 'None', ['Search for Expense Distribution menu/report.'], 'NOT IMPLEMENTED — expense distribution is via allocation mechanism and stats (Total/Excluded/Net Cost Base).', { notImplemented: true, defaultRemarks: 'Use PM cycle stats and Run Cycle Allocation instead.' }),
    tc(uatId(469), 'PM Cycle', 'GL — PM fee bill', 'Verify PM fee bill in General Ledger', 'Sidebar → General Ledger', 'Allocation UAT-456', 'None', ['Search PM fee bill transaction in GL.'], 'PM fee expense and liability entries posted.'),
    tc(uatId(470), 'PM Cycle', 'Audit — allocation run', 'Audit cycle allocation event', 'Settings → Audit Trail', 'Allocation UAT-456', 'None', ['Filter audit for PM allocation event.'], 'Allocation mutation audited.'),
    tc(uatId(471), 'PM Cycle', 'Project without expenses', 'Run allocation on project with zero expenses', NAV_PM, 'Project Green Valley (inactive/minimal)', 'Project: Green Valley', ['Select project with no/minimal expenses.', 'Run Cycle Allocation.'], 'Allocated fee zero or minimal; no erroneous bills.'),
    tc(uatId(472), 'PM Cycle', 'Multiple cycles history', 'Review multiple cycle rows in ledger', `${NAV_PM} → Fee Ledger`, '2+ allocations different months', 'None', ['Run allocation for two different months.', 'Review ledger history.'], 'Multiple cycle/ref rows listed chronologically.'),
    tc(uatId(473), 'PM Cycle', 'Partial payout', 'Record partial PM payout', `${NAV_PM} → Record Payout`, 'Allocation with balance', 'Pay 50% of balance', ['Record partial payout amount.'], 'Paid shows partial; Balance remains.'),
    tc(uatId(474), 'PM Cycle', 'Configure modal cancel', 'Cancel PM configure without saving', `${NAV_PM} → Configure → Cancel`, 'None', 'None', ['Open Configure.', 'Change values.', 'Cancel without save.', 'Reopen — verify unchanged.'], 'Unsaved changes discarded.'),
    tc(uatId(475), 'PM Cycle', 'Real-time sync', 'Second user sees allocation', NAV_PM, 'Two sessions', 'None', ['User A runs allocation.', 'User B refreshes PM cycle view.'], 'Fee ledger updates via real-time sync.'),
    tc(uatId(476), 'PM Cycle', 'License gate', 'Verify PM cycle license gate', 'Sidebar Construction', 'Tenant licensing', 'None', ['Verify PM cycle requires real_estate license.'], 'PM cycle hidden without license.'),
    tc(uatId(477), 'PM Cycle', 'Mobile PM cycle', 'PM cycle on mobile viewport', NAV_PM, 'Viewport <768px', 'None', ['Open PM cycle on mobile/tablet width.'], 'PM cycle UI usable on smaller screens.'),
    tc(uatId(478), 'PM Cycle', 'Global search', 'Find PM Cycle via global search', 'Global search → PM Cycle', 'None', 'None', ['Search PM Cycle.', 'Open result.'], 'Navigates to PM cycle page.'),
    tc(uatId(479), 'PM Cycle', 'Excluded cost recalc', 'Verify Net Cost Base after exclusion change', NAV_PM, 'Allocation not yet run after exclusion change', 'Add new exclusion', ['Change excluded categories.', 'Review Net Cost Base before allocation.'], 'Net Cost Base = Total Expense − Excluded Cost.'),
    tc(uatId(480), 'PM Cycle', 'Chapter completion', 'PM cycle chapter sign-off', 'PM cycle review', 'Ch.9 executed', 'Checklist', ['Config, allocation, payout, reports verified.', 'Complete checklist.'], 'PM cycle E2E complete.'),
  ]),
};

export const CHAPTER_10 = {
  number: 10,
  title: 'Budget Management',
  idRange: 'UAT-481 – UAT-510',
  purpose: 'Verify project budget planning and monitoring: budget creation, revision, spend tracking, and Budget vs Actual variance reporting.',
  businessFlow: `Budget Planner → Select Project → Set category budgets → Monitor spend → Budget vs Actual Report`,
  requiredTestData: [
    'Project: Sunrise Towers',
    'Categories: Construction Material Cost, Civil Works',
    'Budget goals: Material 1,000,000; Civil 2,000,000',
  ],
  dependencies: ['Chapter 2 — project and expense categories', 'Chapter 5 — some spend posted for variance'],
  expectedOutputs: [
    'Category budgets saved per project',
    'Spent and Remaining columns update after bills',
    'Budget vs Actual report shows variance',
  ],
  checklist: [
    'Budget goals entered',
    'Progress % displays',
    'Spent matches construction bills',
    'Budget vs Actual report run',
  ],
  cases: withIds(481, [
    tc(uatId(481), 'Budget', 'Open Budget Planner', 'Navigate to Budget Planner', NAV_BUDGET, 'Financial write access', 'None', ['Sidebar → Financials → Budget Planner.'], 'Project Budget Planner page loads.'),
    tc(uatId(482), 'Budget', 'Select project', 'Select project to configure budgets', `${NAV_BUDGET} → Select a Project to Configure`, 'Sunrise Towers exists', 'Project: Sunrise Towers', ['Select Sunrise Towers from project picker.'], 'Budget grid loads for project expense categories.'),
    tc(uatId(483), 'Budget', 'Summary cards', 'Review budget summary cards', NAV_BUDGET, 'Project selected', 'None', ['Review cards: Total Budget, Total Spent, Remaining.'], 'Summary cards display aggregate figures.'),
    tc(uatId(484), 'Budget', 'Set category budget', 'Enter budget goal for category', `${NAV_BUDGET} → Category row → Budget Goal`, 'Category: Construction Material Cost', 'Budget Goal: 1,000,000', ['Enter 1,000,000 in Budget Goal for Construction Material Cost.', 'Save if explicit save or auto-save.'], 'Budget goal saved; Remaining = Goal − Spent.'),
    tc(uatId(485), 'Budget', 'Set second category budget', 'Enter budget for second category', NAV_BUDGET, 'Project selected', 'Category: Civil Works\nBudget: 2,000,000', ['Enter 2,000,000 for Civil Works category.', 'Save.'], 'Second category budget saved; Total Budget updates.'),
    tc(uatId(486), 'Budget', 'Spent column', 'Verify Spent column after construction bills', NAV_BUDGET, 'Bills posted Ch.5', 'Category with bill spend', ['Review Spent column for categories with posted bills.', 'Compare to known bill amounts.'], 'Spent reflects actual posted expenses by category.'),
    tc(uatId(487), 'Budget', 'Remaining column', 'Verify Remaining calculation', NAV_BUDGET, 'Budget and spend exist', 'None', ['Verify Remaining = Budget Goal − Spent for each row.'], 'Remaining calculates correctly.'),
    tc(uatId(488), 'Budget', 'Progress bar', 'Verify progress percentage', NAV_BUDGET, 'Budget goal and spend', 'None', ['Review Progress column/bar (% used).', 'Verify % = Spent/Goal × 100.'], 'Progress percentage displays accurately.'),
    tc(uatId(489), 'Budget', 'Revise budget — increase', 'Increase budget goal (revision)', NAV_BUDGET, 'Existing budget UAT-484', 'New goal: 1,200,000', ['Change Construction Material Cost budget from 1M to 1.2M.', 'Save.'], 'Budget revised; Remaining recalculated.'),
    tc(uatId(490), 'Budget', 'Revise budget — decrease', 'Decrease budget goal', NAV_BUDGET, 'Existing budget', 'New goal: 900,000', ['Decrease budget goal below spent if allowed.', 'Observe warning if spent exceeds new goal.'], 'System handles over-budget revision per rules.'),
    tc(uatId(491), 'Budget', 'Zero budget category', 'Set zero budget on unused category', NAV_BUDGET, 'Unused category', 'Budget Goal: 0', ['Set unused category budget to 0.'], 'Zero budget saved; progress N/A or 0%.'),
    tc(uatId(492), 'Budget', 'Switch project', 'Configure budget on second project', NAV_BUDGET, 'Green Valley project', 'Project: Green Valley', ['Switch project picker to Green Valley.', 'Enter sample budgets.'], 'Separate budget set per project; no cross-project leakage.'),
    tc(uatId(493), 'Construction', 'Budget vs Actual report', 'Run Budget vs Actual report', 'Project construction → Reports → Operations → Budget vs Actual', 'Budgets UAT-484/485; bills Ch.5', 'Project: Sunrise Towers', ['Open Budget vs Actual report.', 'Select Sunrise Towers.', 'Run.'], 'Report shows budgeted vs actual by category with variance.'),
    tc(uatId(494), 'Budget', 'Report variance — over budget', 'Identify over-budget category in report', 'Budget vs Actual report', 'Category where Spent > Goal', 'None', ['Run report.', 'Locate category over 100% utilization.'], 'Over-budget categories highlighted or show positive variance.'),
    tc(uatId(495), 'Budget', 'Report variance — under budget', 'Identify under-budget category', 'Budget vs Actual report', 'Category with low spend', 'None', ['Locate under-utilized category in report.'], 'Under-budget variance displayed.'),
    tc(uatId(496), 'Budget', 'Export Budget vs Actual', 'Export variance report', 'Budget vs Actual → Export', 'Report data', 'None', ['Export report CSV/Excel if available.'], 'Export file downloads.'),
    tc(uatId(497), 'Budget', 'Import budgets template', 'Download budgets import template', 'Settings → Import Data wizard → Download Budgets Template', 'Admin access', 'None', ['Open Import wizard.', 'Download Budgets Template.', 'Review columns.'], 'Template downloads; import path available (note Phase 2 maturity in wizard).'),
    tc(uatId(498), 'Budget', 'Org-wide budget N/A', 'Verify no org-wide non-project budget', NAV_BUDGET, 'None', 'None', ['Confirm Budget Planner requires project selection.', 'No org-level budget screen.'], 'NOT IMPLEMENTED — budgets are project-specific only.', { notImplemented: true, defaultRemarks: 'Budget Planner is project-scoped by design.' }),
    tc(uatId(499), 'Budget', 'Budget revision audit', 'Audit budget change', 'Settings → Audit Trail', 'Budget revision UAT-489', 'None', ['Filter audit for budget update event.'], 'Budget mutation audited if applicable.'),
    tc(uatId(500), 'Budget', 'Real-time spend update', 'Verify Spent updates after new bill', NAV_BUDGET, 'Two sessions or after new bill', 'New bill 50,000 in category', ['Post new bill in construction.', 'Return to Budget Planner.', 'Verify Spent increased.'], 'Spent column updates after bill posting (real-time or refresh).'),
    tc(uatId(501), 'Budget', 'Empty project budget', 'Open project with no budgets set', NAV_BUDGET, 'Project without budgets', 'Project: Green Valley (fresh)', ['Select project with no budget goals.', 'Review empty grid.'], 'Grid shows categories with zero/null goals.'),
    tc(uatId(502), 'Budget', 'Category column sort', 'Sort/filter budget grid if available', NAV_BUDGET, 'Multiple categories', 'None', ['Use column sort or search if available.'], 'Grid sorting/filtering works.'),
    tc(uatId(503), 'Budget', 'Mobile budget planner', 'Budget Planner on mobile', NAV_BUDGET, 'Viewport <768px', 'None', ['Open Budget Planner on mobile width.'], 'UI usable on smaller screens.'),
    tc(uatId(504), 'Budget', 'Global search', 'Find Budget Planner via search', 'Global search → Budget Planner', 'None', 'None', ['Search Budget Planner.', 'Open result.'], 'Navigates to Budget Planner.'),
    tc(uatId(505), 'Budget', 'Sidebar label', 'Verify sidebar label is Budget Planner', 'Sidebar → Financials', 'None', 'None', ['Confirm menu label is Budget Planner not Budget Management.'], 'Exact label: Budget Planner.'),
    tc(uatId(506), 'Budget', 'Cross-chapter utilization', 'Cross-check Ch.5 budget utilization KPI case', 'Budget Planner + Ch.5 UAT-251', 'Construction bills posted', 'None', ['Compare Budget Planner progress to construction Budget vs Actual.'], 'Figures consistent across Budget Planner and report.'),
    tc(uatId(507), 'Budget', 'Petty cash in spent', 'Verify petty cash vouchers in spent', NAV_BUDGET, 'Petty cash voucher Ch.5 UAT-220', 'Category: Construction Material Cost', ['Review if petty cash voucher increased Spent in matching category.'], 'Petty cash expenses included in spent totals.'),
    tc(uatId(508), 'Budget', 'Permission gate', 'Verify budget access by role', NAV_BUDGET, 'User without financial write', 'Restricted user', ['Log in as user without budget access.', 'Attempt to open Budget Planner.'], 'Access denied or read-only per RBAC.'),
    tc(uatId(509), 'Budget', 'Report print', 'Print Budget vs Actual', 'Budget vs Actual → Print', 'Report data', 'None', ['Print report.'], 'Print preview generates.'),
    tc(uatId(510), 'Budget', 'Chapter completion', 'Budget chapter sign-off', 'Budget module review', 'Ch.10 executed', 'Checklist', ['Budgets set, revised, monitored, report run.', 'Complete checklist.'], 'Budget management E2E complete.'),
  ]),
};

export const CHAPTER_11 = {
  number: 11,
  title: 'Personal Transactions',
  idRange: 'UAT-511 – UAT-540',
  purpose: 'Verify personal finance module for administrators: personal accounts, income, expense, transfers, loans, tasks, and personal reports.',
  businessFlow: `Personal transactions → My wallets → Transactions (Income/Expense/Transfer) → Loan manager → Settings (categories)`,
  requiredTestData: [
    'Admin user only (company_admin or super_admin)',
    'Personal wallet accounts',
    'Sample income 10,000; expense 3,000',
  ],
  dependencies: ['Chapter 1 — admin user', 'Chapter 2 — bank accounts for transfers optional'],
  expectedOutputs: [
    'Personal income and expense recorded',
    'Transfer between wallets works',
    'Loan manager tracks give/receive/repay',
  ],
  checklist: [
    'Admin access verified',
    'Wallets configured',
    'Income/expense/transfer recorded',
    'Loan manager tested',
    'Non-admin blocked',
  ],
  cases: withIds(511, [
    tc(uatId(511), 'Personal', 'Open module — admin', 'Navigate to Personal transactions as admin', NAV_PERSONAL, 'company_admin or super_admin', 'User: admin', ['Log in as admin.', 'Sidebar → Financials → Personal transactions.'], 'Personal transactions page loads with sub-tabs.'),
    tc(uatId(462), 'Personal', 'Access denied — non-admin', 'Verify non-admin blocked', NAV_PERSONAL, 'Non-admin user', 'User: restricted (not admin)', ['Log in as non-admin.', 'Attempt Personal transactions via URL/search.'], 'Access denied message; module not in sidebar for non-admin.'),
    tc(uatId(463), 'Personal', 'My wallets — Add wallet', 'Create personal wallet account', `${NAV_PERSONAL} → My wallets → Add`, 'Admin access', 'Wallet: Personal Cash\nOpening: 5,000', ['Open My wallets tab.', 'Add wallet Personal Cash.', 'Set opening balance.', 'Save.'], 'Wallet created and listed.'),
    tc(uatId(464), 'Personal', 'My wallets — Second wallet', 'Create second wallet for transfers', `${NAV_PERSONAL} → My wallets`, 'Admin access', 'Wallet: Personal Bank\nOpening: 20,000', ['Add second wallet Personal Bank.', 'Save.'], 'Two wallets available for transfers.'),
    tc(uatId(465), 'Personal', 'Transactions — Record income', 'Record personal income', `${NAV_PERSONAL} → Transactions → Add Income`, 'Wallet exists', 'Amount: 10,000\nCategory: Personal income category\nWallet: Personal Cash', ['Add income transaction.', 'Enter amount, category, wallet.', 'Save.'], 'Income recorded; wallet balance increased.'),
    tc(uatId(466), 'Personal', 'Transactions — Record expense', 'Record personal expense', `${NAV_PERSONAL} → Transactions → Add Expense`, 'Wallet exists', 'Amount: 3,000\nCategory: Personal expense\nWallet: Personal Cash', ['Add expense transaction.', 'Save.'], 'Expense recorded; wallet balance decreased.'),
    tc(uatId(467), 'Personal', 'Transactions — Transfer', 'Transfer between personal wallets', `${NAV_PERSONAL} → Transactions → Transfer`, 'Two wallets UAT-463/464', 'From: Personal Bank\nTo: Personal Cash\nAmount: 5,000', ['Create transfer between wallets.', 'Save.'], 'Transfer recorded; both wallet balances updated.'),
    tc(uatId(468), 'Personal', 'Transactions — Edit', 'Edit personal transaction', `${NAV_PERSONAL} → Transactions → Edit`, 'Transaction UAT-465', 'Amount: 10,500', ['Edit income amount.', 'Save.'], 'Transaction updated; balances recalculated.'),
    tc(uatId(469), 'Personal', 'Transactions — Delete', 'Delete personal transaction', `${NAV_PERSONAL} → Transactions → Delete`, 'Deletable test transaction', 'Create temp expense then delete', ['Delete test transaction.', 'Confirm.'], 'Transaction removed; wallet balance restored.'),
    tc(uatId(470), 'Personal', 'Settings — Personal categories', 'Manage personal income/expense categories', `${NAV_PERSONAL} → Settings`, 'Admin access', 'Category: Freelance Income', ['Open Settings tab.', 'Add personal category Freelance Income.', 'Save.'], 'Category available in transaction forms.'),
    tc(uatId(471), 'Personal', 'Loan manager — Give loan', 'Record loan given', `${NAV_PERSONAL} → Loan manager → Give`, 'Admin access', 'Party: Friend A\nAmount: 50,000\nWallet: Personal Bank', ['Open Loan manager.', 'Record Give loan.', 'Save.'], 'Loan given recorded; outstanding balance tracked.'),
    tc(uatId(472), 'Personal', 'Loan manager — Receive repayment', 'Record loan repayment collected', `${NAV_PERSONAL} → Loan manager → Collect/Repay`, 'Loan UAT-471', 'Amount: 10,000', ['Record Collect/Repay on loan.', 'Save.'], 'Outstanding loan balance reduced.'),
    tc(uatId(473), 'Personal', 'Loan manager — Receive loan', 'Record loan received', `${NAV_PERSONAL} → Loan manager → Receive`, 'Admin access', 'Party: Friend B\nAmount: 25,000', ['Record Receive loan.', 'Save.'], 'Loan liability tracked.'),
    tc(uatId(474), 'Personal', 'Loan manager — Repay loan', 'Repay borrowed loan', `${NAV_PERSONAL} → Loan manager → Repay`, 'Loan UAT-473', 'Amount: 5,000', ['Record Repay on received loan.', 'Save.'], 'Loan liability reduced.'),
    tc(uatId(475), 'Personal', 'My Tasks', 'View personal tasks tab', `${NAV_PERSONAL} → My Tasks`, 'Admin access', 'None', ['Open My Tasks tab.', 'Add task if feature available.', 'Mark complete.'], 'Tasks tab functional for personal task tracking.'),
    tc(uatId(476), 'Personal', 'Transactions — Filter by date', 'Filter personal transactions by date range', `${NAV_PERSONAL} → Transactions → date filter`, 'Multiple transactions', 'Range: current month', ['Apply date filter.', 'Verify filtered list.'], 'Only transactions in range shown.'),
    tc(uatId(477), 'Personal', 'Transactions — Filter by wallet', 'Filter by wallet', `${NAV_PERSONAL} → Transactions`, 'Multi-wallet transactions', 'Wallet: Personal Cash', ['Filter by Personal Cash wallet.'], 'Only Personal Cash transactions shown.'),
    tc(uatId(478), 'Personal', 'Global search — Loan Manager', 'Navigate Loan Manager via global search', 'Global search → Loan Manager', 'Admin access', 'None', ['Search Loan Manager under Financials.', 'Open — should route to personal loans or legacy deep link.'], 'Loan Manager accessible (nested under Personal transactions in sidebar).'),
    tc(uatId(479), 'Personal', 'Sidebar label exact', 'Verify sidebar label Personal transactions', 'Sidebar → Financials', 'Admin logged in', 'None', ['Confirm exact label: Personal transactions (lowercase t).'], 'Label matches: Personal transactions.'),
    tc(uatId(480), 'Personal', 'Separation from GL', 'Verify personal transactions separate from business GL', 'Personal transactions vs General Ledger', 'Personal txn UAT-465', 'None', ['Confirm personal transactions do not appear in business General Ledger OR appear in separate personal ledger per design.'], 'Personal finance isolated from company GL per product design.'),
    tc(uatId(481), 'Personal', 'Wallet balance report', 'Review wallet balances on My wallets', `${NAV_PERSONAL} → My wallets`, 'Transactions UAT-465-467', 'None', ['Review current balance on each wallet.', 'Manual reconcile with transactions.'], 'Wallet balances match transaction history.'),
    tc(uatId(482), 'Personal', 'Income report/summary', 'View personal income summary if shown', `${NAV_PERSONAL} → Transactions`, 'Income recorded', 'None', ['Review income totals/summary on transactions view.'], 'Income totals visible.'),
    tc(uatId(483), 'Personal', 'Expense report/summary', 'View personal expense summary', `${NAV_PERSONAL} → Transactions`, 'Expenses recorded', 'None', ['Review expense totals.'], 'Expense totals visible.'),
    tc(uatId(484), 'Personal', 'Transfer report', 'Review transfer history', `${NAV_PERSONAL} → Transactions → type Transfer`, 'Transfer UAT-467', 'None', ['Filter or view transfer transactions.'], 'Transfer history listed.'),
    tc(uatId(485), 'Personal', 'Loan outstanding report', 'Review loan outstanding balances', `${NAV_PERSONAL} → Loan manager`, 'Loans UAT-471/473', 'None', ['Review outstanding balances on loan list.'], 'Outstanding amounts correct per repayments.'),
    tc(uatId(486), 'Personal', 'Category delete guard', 'Attempt delete used personal category', `${NAV_PERSONAL} → Settings`, 'Category used in transaction', 'None', ['Attempt delete category with transactions.', 'Observe guard.'], 'System prevents delete or warns.'),
    tc(uatId(487), 'Personal', 'Mobile personal transactions', 'Personal module on mobile', NAV_PERSONAL, 'Viewport <768px', 'None', ['Open on mobile width.', 'Switch sub-tabs via dropdown.'], 'Mobile layout functional.'),
    tc(uatId(488), 'Personal', 'Audit personal txn N/A', 'Verify personal txn audit scope', 'Settings → Audit Trail', 'Personal transactions', 'None', ['Check if personal transactions appear in enterprise audit.', 'Document scope.'], 'Audit scope documented (may be separate from business audit).'),
    tc(uatId(489), 'Personal', 'Sales user hidden', 'Verify sales_user cannot see Personal transactions', 'Login as sales_user', 'sales_user role', 'None', ['Confirm Personal transactions not in sidebar.'], 'Hidden for sales_user and non-admin.'),
    tc(uatId(540), 'Personal', 'Chapter completion', 'Personal transactions sign-off', 'Personal module review', 'Ch.11 executed', 'Checklist', ['Admin flows complete; non-admin blocked.', 'Complete checklist.'], 'Personal transactions E2E complete.'),
  ]),
};
