import { tc, uatId, withIds } from './helpers.mjs';

const NAV_PAYROLL = 'Sidebar → People → Payroll';

export const CHAPTER_03 = {
  number: 3,
  title: 'Payroll',
  idRange: 'UAT-091 – UAT-150',
  purpose: 'Execute payroll end-to-end: settings, employees, attendance, leave, wizard, processing, SoD approval, payslips, payments, ledger, reports, void/reversal, and audit.',
  businessFlow: `Payroll Settings → Employees → Attendance/Leave → Payroll Wizard → SoD Approval → Payroll Processing → Pay → Reports → Audit`,
  requiredTestData: [
    'Employees: Ali Khan (Finance, 50,000), Sara Ahmed (HR, 45,000)',
    'Department: Finance; Grade: G1',
    'Bank: HBL Current Account (from Ch.2)',
    'Users: admin (Preparer) + approver1 (Approver, different from run creator)',
  ],
  dependencies: ['Chapter 2 — bank account, salary expense categories', 'Two users for SoD approval tests'],
  expectedOutputs: [
    'Payroll run processed and approved',
    'Payslips paid from bank account',
    'Employee ledger reflects accrual and payment',
    'Audit log shows payroll events',
  ],
  checklist: [
    'Payroll settings configured',
    '2+ employees with salary',
    'Attendance/leave recorded',
    'Wizard run GENERATED then APPROVED (SoD)',
    'Salaries paid',
    'Reports and audit verified',
  ],
  cases: withIds(91, [
    tc(uatId(91), 'Payroll', 'Open Payroll Hub', 'Navigate to Payroll module', NAV_PAYROLL, 'User with payroll access', 'None', ['Log in.', 'Sidebar → People → Payroll.'], 'Payroll Hub loads with sub-navigation tabs.'),
    tc(uatId(92), 'Payroll', 'Dashboard KPIs', 'Review payroll dashboard KPI cards', `${NAV_PAYROLL} → Dashboard`, 'Payroll access', 'None', ['Open Dashboard tab.', 'Review 8 KPI cards: Active employees, Payroll runs, Pending approval, etc.'], 'KPI cards display counts/currency.'),
    tc(uatId(93), 'Payroll', 'Settings — Department', 'Create payroll department', `${NAV_PAYROLL} → Settings → Departments → + Add Department`, 'Payroll write access', 'Name: Finance', ['Open Payroll → Settings.', 'Departments → Add Department Finance.', 'Save.'], 'Department listed with staff count.'),
    tc(uatId(94), 'Payroll', 'Settings — Grade', 'Create grade level', `${NAV_PAYROLL} → Settings → Grade Levels → + Add Grade`, 'Payroll settings access', 'Name: G1\nMin: 40000\nMax: 80000', ['Add Grade G1 with salary range.', 'Save.'], 'Grade shows BASE and MULTIPLIER badges.'),
    tc(uatId(95), 'Payroll', 'Settings — Work Week', 'Configure working days', `${NAV_PAYROLL} → Settings → Work Week`, 'Payroll settings access', 'Working days: Mon–Fri', ['Set Mon–Fri as working days.', 'Save.'], 'Work week saved for LOP calculation.'),
    tc(uatId(96), 'Payroll', 'Settings — Leave Type', 'Create leave type', `${NAV_PAYROLL} → Settings → Leave Types`, 'Payroll settings access', 'Name: Annual Leave\nPaid: Yes', ['Add leave type Annual Leave.', 'Save.'], 'Leave type available in Leave Management.'),
    tc(uatId(97), 'Payroll', 'Settings — Earning Type', 'Create earning type', `${NAV_PAYROLL} → Settings → Salary Component Types → Earning`, 'Payroll settings access', 'Name: Housing Allowance\nTaxable: No', ['Add earning type Housing Allowance.', 'Save.'], 'Earning type listed.'),
    tc(uatId(98), 'Payroll', 'Settings — Deduction Type', 'Create deduction type', `${NAV_PAYROLL} → Settings → Salary Component Types → Deduction`, 'Payroll settings access', 'Name: Loan Deduction', ['Add deduction type Loan Deduction.', 'Save.'], 'Deduction type listed.'),
    tc(uatId(99), 'Payroll', 'Settings — GL Defaults', 'Configure payroll GL defaults', `${NAV_PAYROLL} → Settings → Payroll GL Defaults`, 'COA from Ch.2', 'Salary expense: Salaries Expense\nPayable: Salaries Payable\nBank: HBL Current Account', ['Open GL Defaults.', 'Map expense, payable, and bank accounts.', 'Save.'], 'GL defaults saved.'),
    tc(uatId(100), 'Payroll', 'Employees — Add', 'Add employee Ali Khan', `${NAV_PAYROLL} → Employees → + Add Employee`, 'Dept Finance, Grade G1 exist', 'Name: Ali Khan\nDept: Finance\nSalary: 50,000\nAllowance: Housing 5,000', ['Add Employee.', 'Enter personal, job, salary details.', 'Save Employee.'], 'Ali Khan in workforce table.'),
    tc(uatId(101), 'Payroll', 'Employees — Add second', 'Add employee Sara Ahmed', `${NAV_PAYROLL} → Employees → + Add Employee`, 'Dept HR or Finance', 'Name: Sara Ahmed\nSalary: 45,000', ['Add Sara Ahmed.', 'Save.'], 'Second employee in list.'),
    tc(uatId(102), 'Payroll', 'Employees — Search', 'Search workforce', `${NAV_PAYROLL} → Employees → Search workforce`, '2+ employees', 'Search: Ali', ['Type Ali in search box.', 'Wait for results.'], 'Ali Khan returned in paginated search.'),
    tc(uatId(103), 'Payroll', 'Employees — Profile', 'View employee profile tabs', `${NAV_PAYROLL} → Employees → Ali Khan → Profile`, 'Ali Khan exists', 'None', ['Open Ali Khan profile.', 'Review tabs: Summary, Payslips, Ledger, Attendance, Leave, History.'], 'All profile tabs load.'),
    tc(uatId(104), 'Payroll', 'Attendance — Daily entry', 'Record daily attendance', `${NAV_PAYROLL} → Attendance → Daily → + Add`, 'attendance.read permission', 'Employee: Ali Khan\nDate: today\nStatus: Present', ['Open Attendance → Daily.', 'Add attendance for Ali Khan Present.', 'Save.'], 'Attendance row saved.'),
    tc(uatId(105), 'Payroll', 'Attendance — Bulk', 'Bulk attendance entry', `${NAV_PAYROLL} → Attendance → Daily → Bulk`, 'Multiple employees', 'Status: Present for all', ['Open Bulk modal.', 'Apply Present to multiple employees.', 'Save.'], 'Bulk rows created/updated.'),
    tc(uatId(106), 'Payroll', 'Attendance — Monthly sheet', 'View monthly attendance sheet', `${NAV_PAYROLL} → Attendance → Monthly sheet`, 'Attendance records exist', 'Month: current', ['Open Monthly sheet tab.', 'Review grid for current month.'], 'Monthly sheet displays employee attendance grid.'),
    tc(uatId(107), 'Payroll', 'Leave — Request', 'Create leave request', `${NAV_PAYROLL} → Leave Management → Requests → New`, 'leave.read permission', 'Employee: Sara Ahmed\nType: Annual Leave\nDays: 2', ['Create leave request for Sara.', 'Submit.'], 'Request status Pending.'),
    tc(uatId(108), 'Payroll', 'Leave — Approve', 'Approve leave request', `${NAV_PAYROLL} → Leave Management → Approvals`, 'Pending request from UAT-107', 'Request: Sara Annual Leave', ['Open Approvals tab.', 'Approve Sara request.'], 'Status APPROVED; attendance days auto-created.'),
    tc(uatId(109), 'Payroll', 'Leave — Balances', 'View leave balances', `${NAV_PAYROLL} → Leave Management → Balances`, 'Approved leave exists', 'Employee: Sara Ahmed', ['Open Balances tab.', 'Verify Sara balance updated.'], 'Leave balance reflects approved days.'),
    tc(uatId(110), 'Payroll', 'Wizard — Step 1 Period', 'Start payroll wizard period', `${NAV_PAYROLL} → Payroll Wizard`, 'Employees and attendance exist', 'Month: current\nYear: current', ['Open Payroll Wizard.', 'Select current month/year.', 'Continue.'], 'Wizard advances to Attendance step.'),
    tc(uatId(111), 'Payroll', 'Wizard — Step 2 Attendance', 'Review attendance in wizard', `${NAV_PAYROLL} → Payroll Wizard → Attendance`, 'Wizard at step 2', 'None', ['Review attendance summary.', 'Next: LOP review.'], 'Attendance items displayed.'),
    tc(uatId(112), 'Payroll', 'Wizard — Step 3 LOP', 'Review loss-of-pay', `${NAV_PAYROLL} → Payroll Wizard → LOP`, 'Wizard at step 3', 'None', ['Review LOP calculations.', 'Next: Preview.'], 'LOP amounts shown per employee.'),
    tc(uatId(113), 'Payroll', 'Wizard — Step 4 Preview', 'Preview payroll impact', `${NAV_PAYROLL} → Payroll Wizard → Preview`, 'Wizard at step 4', 'None', ['Review gross/net preview.', 'Continue to Generate.'], 'Preview totals match employee salaries.'),
    tc(uatId(114), 'Payroll', 'Wizard — Step 5 Generate', 'Generate attendance summaries', `${NAV_PAYROLL} → Payroll Wizard → Generate`, 'Wizard at step 5', 'None', ['Click Generate summaries.', 'Wait for completion.'], 'Summaries generated successfully.'),
    tc(uatId(115), 'Payroll', 'Wizard — Step 6 Process', 'Process payslips', `${NAV_PAYROLL} → Payroll Wizard → Process`, 'Summaries generated', 'None', ['Click Process payslips.', 'Wait for run status GENERATED.'], 'Payslips created; run status GENERATED.'),
    tc(uatId(116), 'Payroll', 'Wizard — Step 7 SoD block', 'Creator cannot approve own run', `${NAV_PAYROLL} → Payroll Wizard → Approval`, 'User A created run; same user on step 7', 'User: admin (creator)', ['As run creator on Approval step.', 'Observe Approve button disabled.', 'Read SoD policy message.'], 'Approve disabled; Waiting For Approver shown.'),
    tc(uatId(117), 'Payroll', 'SoD — Independent approve', 'Second user approves run', `${NAV_PAYROLL} → Payroll Wizard → Approval OR Payroll Processing banner`, 'approver1 logged in; not run creator', 'User: approver1', ['Log in as approver1.', 'Open Wizard step 7 or Processing approval banner.', 'Click Approve Payroll Run.'], 'Run status APPROVED.'),
    tc(uatId(118), 'Payroll', 'Processing — Open cycle', 'Open Payroll Processing view', `${NAV_PAYROLL} → Payroll Processing`, 'Approved run exists', 'Period: current month', ['Open Payroll Processing.', 'Select current period/run.'], 'Employee tree and payslip table load.'),
    tc(uatId(119), 'Payroll', 'Processing — Pay single', 'Pay single payslip', `${NAV_PAYROLL} → Payroll Processing → Pay`, 'APPROVED run; unpaid payslip', 'Employee: Ali Khan\nAccount: HBL Current Account\nAmount: net pay', ['Select Ali Khan payslip.', 'Click Pay → Pay Salary modal.', 'Select bank account.', 'Confirm Payment.'], 'Payslip marked paid; GL transaction posted.'),
    tc(uatId(120), 'Payroll', 'Processing — Bulk pay', 'Bulk pay remaining payslips', `${NAV_PAYROLL} → Payroll Processing → Pay (N)`, 'APPROVED run; unpaid payslips', 'Account: HBL Current Account', ['Select unpaid payslip checkboxes.', 'Click Pay (N) toolbar.', 'Confirm bulk payment.'], 'All selected payslips paid.'),
    tc(uatId(121), 'Payroll', 'Processing — Pay before approve blocked', 'Verify pay blocked on unapproved run', `${NAV_PAYROLL} → Payroll Processing`, 'GENERATED (not APPROVED) run', 'New test run if needed', ['Create new run without approval.', 'Attempt Pay on payslip.'], 'Payment blocked: run must be APPROVED.'),
    tc(uatId(122), 'Payroll', 'Processing — Edit payslip', 'Edit payslip amounts', `${NAV_PAYROLL} → Payroll Processing → Edit`, 'Unpaid or approved run per rules', 'Adjust allowance +500', ['Click Edit on payslip.', 'Adjust amount.', 'Save.'], 'Net recalculated; audit event recorded.'),
    tc(uatId(123), 'Payroll', 'Processing — Delete unpaid payslip', 'Delete unpaid payslip', `${NAV_PAYROLL} → Payroll Processing → Delete`, 'Unpaid payslip on test run', 'Test employee payslip', ['Delete unpaid payslip.', 'Confirm.'], 'Payslip removed; totals updated.'),
    tc(uatId(124), 'Payroll', 'Processing — Employee ledger', 'View employee ledger in processing', `${NAV_PAYROLL} → Payroll Processing → filter Ledger`, 'Paid payslip exists', 'Employee: Ali Khan', ['Select Ali Khan.', 'Filter Ledger.', 'Review transactions.'], 'Ledger shows accrual and payment entries.'),
    tc(uatId(125), 'Payroll', 'Payslips — Register', 'View payslips register', `${NAV_PAYROLL} → Payslips`, 'Paid payslips exist', 'Year: current', ['Open Payslips tab.', 'Filter by year.', 'Locate Ali Khan payslip.'], 'Payslip listed in register.'),
    tc(uatId(126), 'Payroll', 'Payslips — View/Print', 'View and print payslip', `${NAV_PAYROLL} → Payslips OR Employee Profile → Payslips`, 'Paid payslip', 'Employee: Ali Khan', ['Open payslip detail.', 'Click Print/View.'], 'Payslip PDF or print preview displays.'),
    tc(uatId(127), 'Payroll', 'Payment History', 'View payment history', `${NAV_PAYROLL} → Payment History`, 'Completed payments exist', 'None', ['Open Payment History tab.', 'Review completed payment records.'], 'Payment history lists paid runs/transactions.'),
    tc(uatId(128), 'Payroll', 'Reports — Summary', 'Run payroll summary report', `${NAV_PAYROLL} → Reports → Summary`, 'Processed run exists', 'Period: current month', ['Open Reports → Summary tab.', 'Run/export report.'], 'Summary report displays run totals.'),
    tc(uatId(129), 'Payroll', 'Reports — Register', 'Run payroll register report', `${NAV_PAYROLL} → Reports → Register`, 'Processed run', 'None', ['Open Register tab.', 'Export CSV if available.'], 'Register lists all payslips for period.'),
    tc(uatId(130), 'Payroll', 'Reports — Liability', 'Run liability report', `${NAV_PAYROLL} → Reports → Liability`, 'Unpaid/paid mix', 'None', ['Open Liability tab.', 'Review outstanding amounts.'], 'Liability report balances correctly.'),
    tc(uatId(131), 'Payroll', 'Reports — Journal', 'Run payroll journal report', `${NAV_PAYROLL} → Reports → Journal`, 'Approved/paid run', 'None', ['Open Journal tab.', 'Verify accrual and payment entries.'], 'Journal mirrors GL postings.'),
    tc(uatId(132), 'Payroll', 'Reports — LOP', 'Run LOP report', `${NAV_PAYROLL} → Reports → LOP`, 'LOP data exists', 'None', ['Open LOP tab.', 'Review loss-of-pay details.'], 'LOP report displays deductions.'),
    tc(uatId(133), 'Payroll', 'Audit Log — View', 'View payroll audit log', `${NAV_PAYROLL} → Audit Log`, 'API mode; payroll mutations done', 'None', ['Open Audit Log tab.', 'Review columns: When, Event, Who, Entity, Summary.'], 'Payroll audit events listed.'),
    tc(uatId(134), 'Payroll', 'Audit Log — Run Approved', 'Verify run approved event', `${NAV_PAYROLL} → Audit Log → filter`, 'Run approved in UAT-117', 'Event: Run Approved', ['Filter Run Approved.', 'Locate approval event.'], 'Shows approver name and timestamp.'),
    tc(uatId(135), 'Payroll', 'Void — Unpaid payslip delete', 'Delete vs void distinction', `${NAV_PAYROLL} → Payroll Processing`, 'Unpaid payslip on test run', 'Unpaid payslip', ['Delete unpaid payslip (not Void).', 'Confirm removed.'], 'Unpaid payslip deleted (not voided).'),
    tc(uatId(136), 'Payroll', 'Void — Paid payslip void', 'Void fully paid payslip', `${NAV_PAYROLL} → Payroll Processing → Void`, 'Fully paid test payslip', 'Reason: UAT test void', ['Select fully paid payslip.', 'Click Void (not Delete).', 'Enter required reason.', 'Confirm void warning.'], 'Payslip voided; toast warns to reverse payment in Accounting.'),
    tc(uatId(137), 'Payroll', 'Reverse — Payment reversal', 'Reverse payroll payment', `${NAV_PAYROLL} → Payroll Processing → Reverse Payment`, 'Paid transaction to reverse', 'Transaction from void test', ['Open Reverse Payroll Payment modal.', 'Confirm reversal.'], 'Payment reversed; payslip state updated.'),
    tc(uatId(138), 'Payroll', 'Unapprove — Revert approved run', 'Revert APPROVED run to GENERATED', `${NAV_PAYROLL} → Payroll Processing → Revert to generated`, 'Approved run with NO payments', 'Test run without payments', ['Click Revert to generated on approval panel.', 'Confirm.'], 'Run returns to GENERATED status.'),
    tc(uatId(139), 'Payroll', 'Unapprove blocked when paid', 'Unapprove blocked if payslips paid', `${NAV_PAYROLL} → Payroll Processing`, 'Approved run WITH payments', 'Run from UAT-119/120', ['Attempt Revert to generated.', 'Observe error.'], 'Error: cannot unapprove when payslips have payments.'),
    tc(uatId(140), 'Payroll', 'Past period wizard', 'Open past period payroll wizard', `${NAV_PAYROLL} → Payroll Processing → Payroll wizard (past period)`, 'Payroll admin', 'Prior month/year', ['Click Payroll wizard (past period).', 'Select prior month.', 'Open wizard.'], 'Wizard opens at step 1 with selected period.'),
    tc(uatId(141), 'Payroll', 'Dashboard — Awaiting approval banner', 'Verify awaiting approval banner', `${NAV_PAYROLL} → Dashboard`, 'GENERATED unapproved run', 'None', ['Create unapproved run.', 'Check Dashboard Awaiting Approval panel.'], 'Banner shows count needing approver.'),
    tc(uatId(142), 'Payroll', 'Dashboard — Ready to pay', 'Verify ready to pay banner', `${NAV_PAYROLL} → Dashboard`, 'APPROVED run exists', 'None', ['After approval, check Ready to Pay panel.'], 'Banner directs to Processing for disbursement.'),
    tc(uatId(143), 'Payroll', 'RBAC — Attendance tab hidden', 'Verify attendance tab permission', NAV_PAYROLL, 'User without attendance.read', 'Restricted user', ['Log in as user without attendance.read.', 'Verify Attendance tab hidden.'], 'Attendance tab not shown without permission.'),
    tc(uatId(144), 'Payroll', 'RBAC — Leave tab hidden', 'Verify leave tab permission', NAV_PAYROLL, 'User without leave.read', 'Restricted user', ['Log in without leave.read.', 'Verify Leave Management hidden.'], 'Leave tab hidden per RBAC.'),
    tc(uatId(145), 'Payroll', 'Void Payroll Run UI', 'Verify void entire run UI', `${NAV_PAYROLL} → Payroll Processing`, 'None', 'None', ['Search for Void Payroll Run action on run level.'], 'NOT IMPLEMENTED — API exists; UI modal not wired in PayrollHub.', { notImplemented: true }),
    tc(uatId(146), 'Payroll', 'Approval Matrix config', 'Verify configurable approval matrix for payroll', 'Settings → Security — Approval Matrix', 'None', 'None', ['Check if payroll uses approval matrix vs hard-coded SoD.'], 'NOT IMPLEMENTED — SoD hard-coded: creator ≠ approver.', { notImplemented: true }),
    tc(uatId(147), 'Payroll', 'Statutory tax / EOBI', 'Verify statutory payroll compliance', NAV_PAYROLL, 'None', 'None', ['Search for tax/EOBI/PF statutory modules.'], 'NOT IMPLEMENTED — no statutory compliance engine.', { notImplemented: true }),
    tc(uatId(148), 'Payroll', 'Employee self-service full hub', 'Verify employee role limited access', NAV_PAYROLL, 'Employee-role user', 'Employee user account', ['Log in as employee role.', 'Verify limited to self profile only.'], 'Employee sees profile only; not full admin hub (partial by design).'),
    tc(uatId(149), 'Payroll', 'Attendance informational note', 'Confirm attendance feeds wizard', `${NAV_PAYROLL} → Attendance`, 'Attendance page loaded', 'None', ['Read attendance page guidance.', 'Cross-check wizard step 2 uses attendance summaries.'], 'Attendance data flows to wizard despite informational label.'),
    tc(uatId(150), 'Payroll', 'Chapter completion', 'Payroll chapter sign-off', 'Payroll module review', 'Ch.3 cases executed', 'Chapter checklist', ['Verify settings, employees, run approved, paid, reports, audit.', 'Complete checklist.'], 'Payroll E2E path complete for regression baseline.'),
  ]),
};
