import { tc, uatId, withIds } from './helpers.mjs';

const NAV_RENTAL = 'Sidebar → Rental → Rental';

export const CHAPTER_06 = {
  number: 6,
  title: 'Rental Management',
  idRange: 'UAT-281 – UAT-350',
  purpose: 'Manage rental operations: setup, agreements, invoices, payments, service charges, bills, payouts (owner settlement), and rental reports.',
  businessFlow: `Rental setup → Agreement → Invoice → Payment → Payouts (Owner Income) → Owner Rental Income Report`,
  requiredTestData: [
    'Building: Marina Heights; Unit: MH-201',
    'Owner: Owner Ali; Tenant: Fatima Tenant',
    'Monthly rent: 50,000; Security deposit: 100,000',
    'Bank: HBL Current Account',
  ],
  dependencies: ['Chapter 2 — rental assets and contacts', 'rental license module enabled'],
  expectedOutputs: [
    'Rental agreement active',
    'Rent invoices generated and paid',
    'Owner payout recorded',
    'Tenant ledger balanced',
  ],
  checklist: [
    'Rental setup complete (building, unit, owner, tenant)',
    'Agreement signed/active',
    'Invoice paid',
    'Owner payout processed',
    'Ledger reports verified',
  ],
  cases: withIds(281, [
    tc(uatId(281), 'Rental', 'Open module', 'Navigate to Rental management', NAV_RENTAL, 'rental license', 'None', ['Sidebar → Rental → Rental.'], 'Rental shell loads with sub-navigation.'),
    tc(uatId(282), 'Rental', 'Rental setup — Buildings', 'Configure rental building', `${NAV_RENTAL} → Operations → Rental setup → Buildings`, 'Rental access', 'Building: Marina Heights', ['Open Rental setup.', 'Buildings tab → verify/add Marina Heights.'], 'Building listed in rental setup.'),
    tc(uatId(283), 'Rental', 'Rental setup — Properties (Units)', 'Configure rental unit', `${NAV_RENTAL} → Rental setup → Properties (Units)`, 'Building exists', 'Unit: MH-201\nBuilding: Marina Heights', ['Add or verify unit MH-201.', 'Link to building.', 'Save.'], 'Rental unit configured.'),
    tc(uatId(284), 'Rental', 'Rental setup — Owners', 'Configure rental owner', `${NAV_RENTAL} → Rental setup → Owners`, 'Contact Owner Ali', 'Owner: Owner Ali', ['Add/link owner in rental setup.', 'Save.'], 'Owner available for agreements/payouts.'),
    tc(uatId(285), 'Rental', 'Rental setup — Tenants', 'Configure tenant', `${NAV_RENTAL} → Rental setup → Tenants`, 'Contact Fatima Tenant', 'Tenant: Fatima Tenant', ['Add tenant Fatima Tenant.', 'Save.'], 'Tenant listed.'),
    tc(uatId(286), 'Rental', 'Rental setup — Brokers', 'Configure rental broker', `${NAV_RENTAL} → Rental setup → Brokers`, 'Broker contact exists', 'Broker: Broker One', ['Add broker if separate from selling.', 'Save.'], 'Broker available for rental agreements.'),
    tc(uatId(287), 'Rental', 'Analytics', 'View rental analytics', `${NAV_RENTAL} → Operations → Analytics`, 'Rental data', 'None', ['Open Analytics.'], 'Rental analytics dashboard loads.'),
    tc(uatId(288), 'Rental', 'Agreements — New', 'Create rental agreement', `${NAV_RENTAL} → Operations → Agreements → New`, 'Unit MH-201, tenant, owner', 'Tenant: Fatima Tenant\nUnit: MH-201\nRent: 50,000/month\nStart: 1st of next month\nDeposit: 100,000', ['Open Agreements.', 'New rental agreement.', 'Enter terms.', 'Save/activate.'], 'Rental agreement created.'),
    tc(uatId(289), 'Rental', 'Agreements — Edit', 'Edit rental agreement', `${NAV_RENTAL} → Agreements → Edit`, 'Agreement UAT-288', 'Rent: 52,000', ['Edit agreement rent amount.', 'Save.'], 'Agreement updated.'),
    tc(uatId(290), 'Rental', 'Agreements — Expiry', 'Set agreement end date', `${NAV_RENTAL} → Agreements`, 'Agreement UAT-288', 'End date: +12 months', ['Set agreement expiry/end date.', 'Save.'], 'End date saved for expiry report.'),
    tc(uatId(291), 'Rental', 'Invoices — Generate', 'Generate rent invoices', `${NAV_RENTAL} → Operations → Invoices`, 'Active agreement', 'Monthly rent invoices', ['Open Invoices.', 'Generate invoices from agreement schedule.', 'Verify invoice list.'], 'Rent invoices created.'),
    tc(uatId(292), 'Rental', 'Invoices — Receive payment', 'Record tenant rent payment', `${NAV_RENTAL} → Invoices → Rental Payment`, 'Unpaid rent invoice', 'Amount: 50,000\nAccount: HBL Current Account', ['Select rent invoice.', 'Rental Payment / Receive Payment.', 'Confirm.'], 'Invoice paid; tenant balance updated.'),
    tc(uatId(293), 'Rental', 'Invoices — Bulk payment', 'Bulk rent payment', `${NAV_RENTAL} → Invoices → Bulk Payment`, 'Multiple unpaid invoices', 'Select 2 invoices', ['Bulk pay selected invoices.'], 'Multiple invoices marked paid.'),
    tc(uatId(294), 'Rental', 'Collections Analytics', 'View rental collections', `${NAV_RENTAL} → Operations → Collections`, 'Payments UAT-292', 'None', ['Open Collections Analytics.'], 'Collections KPIs reflect payments.'),
    tc(uatId(295), 'Rental', 'Monthly Service Charges', 'Configure service charges', `${NAV_RENTAL} → Operations → Monthly Service Charges`, 'Building/units exist', 'Service charge: 5,000/month', ['Open Monthly Service Charges.', 'Configure charge for building/unit.', 'Save.'], 'Service charges configured.'),
    tc(uatId(296), 'Rental', 'Service charge invoice', 'Generate service charge invoice', `${NAV_RENTAL} → Invoices or Service Charges`, 'Service charge UAT-295', 'Amount: 5,000', ['Generate service charge invoice.', 'Verify on Invoices list.'], 'Service charge invoice created.'),
    tc(uatId(297), 'Rental', 'Bills — Rental expense bill', 'Record rental property expense bill', `${NAV_RENTAL} → Operations → Bills`, 'Vendor for maintenance', 'Vendor: ABC Supplies\nAmount: 10,000\nBuilding: Marina Heights', ['Add rental context bill.', 'Save/post.'], 'Rental expense bill recorded.'),
    tc(uatId(298), 'Rental', 'Expense Analytics', 'View rental expense analytics', `${NAV_RENTAL} → Operations → Expense Analytics`, 'Bills exist', 'None', ['Open Expense Analytics.'], 'Rental expense dashboard loads.'),
    tc(uatId(299), 'Rental', 'Payouts — Owner Income', 'Process owner income payout', `${NAV_RENTAL} → Operations → Payouts → Owner Income`, 'Rent collected', 'Owner: Owner Ali\nAmount: net after deductions', ['Open Payouts.', 'Owner Income chip/tab.', 'Pay owner share.', 'Confirm.'], 'Owner payout recorded (owner settlement via Payouts).'),
    tc(uatId(300), 'Rental', 'Payouts — Broker Commission', 'Process broker commission payout', `${NAV_RENTAL} → Payouts → Broker Commission`, 'Broker on agreement', 'Broker: Broker One', ['Process broker commission payout.'], 'Broker commission paid.'),
    tc(uatId(301), 'Rental', 'Payouts — Security Deposit', 'Process security deposit payout/receipt', `${NAV_RENTAL} → Payouts → Security Deposit`, 'Deposit on agreement', 'Deposit: 100,000', ['Record security deposit receive/payout as applicable.'], 'Security deposit transaction recorded.'),
    tc(uatId(302), 'Rental', 'Payouts — Ledger expand', 'View owner rental income ledger', `${NAV_RENTAL} → Payouts → expand row → Rental Income Ledger`, 'Payout UAT-299', 'Owner: Owner Ali', ['Expand payout row.', 'Review Rental Income Ledger detail.'], 'Owner income ledger entries visible.'),
    tc(uatId(303), 'Rental', 'Visual layout', 'View rental visual layout', `${NAV_RENTAL} → Property views → Visual layout`, 'Units exist', 'Building: Marina Heights', ['Open Visual layout.'], 'Visual property layout displays units.'),
    tc(uatId(304), 'Rental', 'Tabular layout', 'View rental tabular layout', `${NAV_RENTAL} → Property views → Tabular layout`, 'Units exist', 'None', ['Open Tabular layout.'], 'Tabular unit grid displays.'),
    tc(uatId(305), 'Rental', 'Report — Agreement Expiry', 'Run Agreement Expiry report', `${NAV_RENTAL} → Reports → Analysis → Agreement Expiry`, 'Agreement with end date', 'None', ['Run Agreement Expiry report.'], 'Expiring agreements listed.'),
    tc(uatId(306), 'Rental', 'Report — Building Analysis', 'Run Building Analysis', `${NAV_RENTAL} → Reports → Analysis → Building Analysis`, 'Building data', 'Building: Marina Heights', ['Run Building Analysis.'], 'Building metrics displayed.'),
    tc(uatId(307), 'Rental', 'Report — BM Analysis', 'Run BM Analysis report', `${NAV_RENTAL} → Reports → Analysis → BM Analysis`, 'Rental data', 'None', ['Run BM Analysis.'], 'BM analysis report generates.'),
    tc(uatId(308), 'Rental', 'Report — Invoice & Payment Analysis', 'Run Invoice & Payment Analysis', `${NAV_RENTAL} → Reports → Analysis → Invoice & Payment Analysis`, 'Invoices/payments', 'None', ['Run report.'], 'Invoice and payment analysis displayed.'),
    tc(uatId(309), 'Rental', 'Report — Owner Rental Income', 'Run Owner Rental Income ledger report', `${NAV_RENTAL} → Reports → Ledgers → Owner Rental Income`, 'Owner payouts', 'Owner: Owner Ali', ['Run Owner Rental Income.', 'Select owner.'], 'Owner rental income ledger report generates.'),
    tc(uatId(310), 'Rental', 'Report — Owner Income Summary', 'Run Owner Rental Income Summary', `${NAV_RENTAL} → Reports → Ledgers → Owner Rental Income Summary`, 'Owner data', 'None', ['Run summary report.'], 'Summary totals by owner.'),
    tc(uatId(311), 'Rental', 'Report — Service Charges Deduction', 'Run Service Charges Deduction', `${NAV_RENTAL} → Reports → Ledgers → Service Charges Deduction`, 'Service charges', 'None', ['Run report.'], 'Service charge deductions listed.'),
    tc(uatId(312), 'Rental', 'Report — Tenant Ledger', 'Run Tenant Ledger', `${NAV_RENTAL} → Reports → Ledgers → Tenant Ledger`, 'Tenant Fatima', 'Tenant: Fatima Tenant', ['Run Tenant Ledger for Fatima.'], 'Tenant invoices/payments/balance shown.'),
    tc(uatId(313), 'Rental', 'Report — Rental Receivable', 'Run Rental Receivable', `${NAV_RENTAL} → Reports → Ledgers → Rental Receivable`, 'Unpaid invoices optional', 'None', ['Run Rental Receivable report.'], 'Outstanding receivables listed.'),
    tc(uatId(314), 'Rental', 'Report — Vendor Ledger', 'Run Vendor Ledger (rental)', `${NAV_RENTAL} → Reports → Ledgers → Vendor Ledger`, 'Rental bills', 'Vendor: ABC Supplies', ['Run Vendor Ledger rental context.'], 'Vendor ledger for rental expenses.'),
    tc(uatId(315), 'Rental', 'Report — Security Deposit', 'Run Security Deposit report', `${NAV_RENTAL} → Reports → Ledgers → Security Deposit`, 'Deposit UAT-301', 'None', ['Run Security Deposit report.'], 'Security deposit balances listed.'),
    tc(uatId(316), 'Rental', 'Report — Broker Fees', 'Run Broker Fees report', `${NAV_RENTAL} → Reports → Ledgers → Broker Fees`, 'Broker payouts', 'None', ['Run Broker Fees report.'], 'Broker fees summarized.'),
    tc(uatId(317), 'Rental', 'Owner settlement menu', 'Verify no dedicated Owner Settlement menu', NAV_RENTAL, 'None', 'None', ['Search for Owner Settlement menu item.'], 'NOT IMPLEMENTED as menu name — use Payouts for owner settlement.', { notImplemented: true, defaultRemarks: 'Use Rental → Payouts → Owner Income instead.' }),
    tc(uatId(318), 'Rental', 'Dedicated rental payments page', 'Verify payments on Invoices not separate page', `${NAV_RENTAL} → Invoices`, 'None', 'None', ['Confirm no top-level Rental Payments menu.'], 'Payments embedded in Invoices sub-tab.'),
    tc(uatId(319), 'Rental', 'Ownership transfers', 'Verify ownership transfers removed', NAV_RENTAL, 'None', 'None', ['Search Ownership transfers in rental nav.'], 'NOT IMPLEMENTED — removed; redirects to Agreements.'),
    tc(uatId(320), 'Rental', 'Legacy deep links', 'Test global search rental deep links', 'Global search → Rental Invoices', 'None', 'None', ['Search Rental Invoices, Rental Agreements, Owner Payouts, Rental Setup.'], 'Each opens correct Rental sub-view.'),
    tc(uatId(321), 'Rental', 'Settings Assets — Rental group', 'Cross-check Settings → Assets rental', 'Settings → Assets → Rental', 'Assets from Ch.2', 'Rental Building/Properties', ['Verify rental assets in Settings mirror Rental setup.'], 'Consistent master data between Settings and Rental setup.'),
    tc(uatId(322), 'Rental', 'Agreement — Deposit invoice', 'Generate security deposit invoice', `${NAV_RENTAL} → Invoices`, 'Agreement with deposit', 'Deposit: 100,000', ['Generate deposit invoice if separate from rent.'], 'Deposit invoice on invoice list.'),
    tc(uatId(323), 'Rental', 'Invoice print', 'Print rental invoice', `${NAV_RENTAL} → Invoices → Print`, 'Rent invoice', 'None', ['Print rental invoice.'], 'Print preview/PDF generates.'),
    tc(uatId(324), 'Rental', 'Real-time invoice sync', 'Verify invoice payment sync', `${NAV_RENTAL} → Invoices (2nd session)`, 'Two users', 'None', ['User A records payment.', 'User B sees updated balance.'], 'Real-time sync updates invoice status.'),
    tc(uatId(325), 'Rental', 'Audit — agreement', 'Audit rental agreement creation', 'Settings → Audit Trail', 'Agreement UAT-288', 'None', ['Filter audit for rental agreement.'], 'Agreement creation audited.'),
    tc(uatId(326), 'Rental', 'GL — rent payment', 'Verify rent payment in GL', 'Sidebar → General Ledger', 'Payment UAT-292', 'None', ['Locate rent payment in GL.'], 'Bank debit and AR credit posted.'),
    tc(uatId(327), 'Rental', 'Custom Reports hidden', 'Rental custom reports hidden from nav', 'Global search', 'None', 'None', ['Search Custom Reports rental.'], 'Hidden from sub-nav but routable.'),
    tc(uatId(328), 'Rental', 'Mobile rental nav', 'Rental sub-nav on mobile', NAV_RENTAL, 'Viewport <768px', 'None', ['Use mobile dropdown for Operations/Reports.'], 'Mobile navigation works.'),
    tc(uatId(329), 'Rental', 'License gate rental', 'Verify rental license gate', 'Sidebar Rental item', 'Tenant licensing', 'None', ['Verify Rental sidebar requires rental license.'], 'Rental hidden without rental license.'),
    tc(uatId(330), 'Rental', 'Payouts — Receive action', 'Use Receive on payout row', `${NAV_RENTAL} → Payouts → Receive`, 'Applicable payout type', 'None', ['Click Receive where shown on payout row.'], 'Receive action processes inbound payout.'),
    tc(uatId(331), 'Rental', 'Agreement renewal', 'Renew or extend agreement', `${NAV_RENTAL} → Agreements`, 'Expiring agreement', 'Extend 12 months', ['Extend agreement end date or renew.', 'Save.'], 'Agreement extended; new invoices may generate.'),
    tc(uatId(332), 'Rental', 'Vacant unit status', 'Mark unit vacant after agreement ends', `${NAV_RENTAL} → Rental setup → Properties`, 'Ended agreement test', 'Unit: test vacant', ['Update unit occupancy status if field exists.'], 'Unit status reflects vacancy.'),
    tc(uatId(333), 'Rental', 'Report export — Tenant Ledger', 'Export Tenant Ledger', `${NAV_RENTAL} → Reports → Tenant Ledger → Export`, 'Ledger data', 'None', ['Export tenant ledger.'], 'Export file downloads.'),
    tc(uatId(334), 'Rental', 'Collections — overdue', 'Review overdue rent in collections', `${NAV_RENTAL} → Collections`, 'Past due invoice optional', 'None', ['Review overdue metrics.'], 'Overdue rent highlighted when applicable.'),
    tc(uatId(335), 'Rental', 'Bills — Pay rental bill', 'Pay rental maintenance bill', `${NAV_RENTAL} → Bills → Pay`, 'Bill UAT-297', 'Account: HBL', ['Pay rental expense bill.'], 'Bill paid; expense posted.'),
    tc(uatId(336), 'Rental', 'WhatsApp rent reminder', 'Communication template for rent', 'Settings → Preferences → Communication', 'Templates configured', 'Rent reminder template', ['Review rent-related WhatsApp/print templates.'], 'Communication templates available.'),
    tc(uatId(337), 'Rental', 'Workflow — agreement approval', 'Submit rental agreement for approval', `${NAV_RENTAL} → Agreements → Submit`, 'Workflow enabled', 'New agreement', ['Submit agreement for workflow if required.'], 'Workflow status updates.'),
    tc(uatId(338), 'Rental', 'Multi-building owner', 'Owner with multiple buildings', `${NAV_RENTAL} → Rental setup`, 'Second building optional', 'Owner: Owner Ali', ['Assign same owner to multiple buildings if applicable.'], 'Owner linked across buildings.'),
    tc(uatId(339), 'Rental', 'Report — Owner ledger cross-check', 'Cross-check payout vs Owner Rental Income report', `${NAV_RENTAL} → Payouts + Reports`, 'Payout UAT-299', 'Owner: Owner Ali', ['Compare payout amount to Owner Rental Income report totals.'], 'Figures reconcile between payout and report.'),
    tc(uatId(340), 'Rental', 'Tenant portal N/A', 'Verify no tenant self-service portal', 'Application menus', 'None', 'None', ['Search for tenant portal/login.'], 'NOT IMPLEMENTED — tenant management is admin-side only.'),
    tc(uatId(341), 'Rental', 'KPI panel — Rental Inv.', 'KPI shortcut to rental invoices', 'Dashboard → KPI → Rental Inv.', 'None', 'None', ['Use KPI panel Rental Inv. shortcut.'], 'Navigates to rental invoices view.'),
    tc(uatId(342), 'Rental', 'Invoice partial payment', 'Partial rent payment', `${NAV_RENTAL} → Invoices → Payment`, 'Unpaid invoice', 'Pay 50% of rent', ['Record partial payment.'], 'Invoice shows partial paid balance.'),
    tc(uatId(343), 'Rental', 'Agreement — Broker link', 'Link broker on rental agreement', `${NAV_RENTAL} → Agreements → Edit`, 'Broker One exists', 'Broker: Broker One\nCommission: 1 month', ['Add broker to agreement.', 'Save.'], 'Broker commission rules on agreement.'),
    tc(uatId(344), 'Rental', 'Payouts — Security Deposit Ledger', 'View Security Deposit Ledger expand', `${NAV_RENTAL} → Payouts → expand`, 'Deposit transactions', 'None', ['Expand row → Security Deposit Ledger.'], 'Deposit ledger entries visible.'),
    tc(uatId(345), 'Rental', 'Expense Analytics drill', 'Drill rental expenses by building', `${NAV_RENTAL} → Expense Analytics`, 'Bills posted', 'Building: Marina Heights', ['Filter/drill by building if available.'], 'Expenses attributed to building.'),
    tc(uatId(346), 'Rental', 'Settings — Rental invoice settings', 'Review rental invoice settings', 'Settings → Preferences (rental invoice defaults if present)', 'None', 'None', ['Review rental invoice numbering/defaults in Settings.'], 'Rental invoice settings accessible.'),
    tc(uatId(347), 'Rental', 'Agreement inactive', 'Deactivate/cancel agreement', `${NAV_RENTAL} → Agreements`, 'Test agreement', 'Cancel test agreement', ['Cancel or mark agreement inactive.', 'Confirm invoice generation stops.'], 'Agreement cancelled per system rules.'),
    tc(uatId(348), 'Rental', 'Report — BM Analysis filter', 'Filter BM Analysis by building', `${NAV_RENTAL} → Reports → BM Analysis`, 'Multi-building', 'Building: Marina Heights', ['Run with building filter.'], 'Filtered analysis displayed.'),
    tc(uatId(349), 'Rental', 'Audit — owner payout', 'Audit owner payout event', 'Settings → Audit Trail', 'Payout UAT-299', 'None', ['Filter audit for owner payout.'], 'Payout mutation audited.'),
    tc(uatId(350), 'Rental', 'Chapter completion', 'Rental chapter sign-off', 'Rental module review', 'Ch.6 executed', 'Checklist', ['Verify setup → agreement → invoice → payment → payout → reports.', 'Complete checklist.'], 'Rental management E2E complete.'),
  ]),
};
