/**
 * PrintReportLayout — reusable wrapper for formal report printable areas.
 * Provides company branding, report title, optional metadata, and footer.
 * Use inside an element with id="printable-area" (or custom id passed to usePrintReport).
 */

import React from 'react';
import { useAuth } from '../../context/AuthContext';
import ReportHeader from '../reports/ReportHeader';
import ReportFooter from '../reports/ReportFooter';

export interface PrintReportLayoutProps {
  /** Report title shown below company header */
  title?: string;
  /** Secondary line (date range, filters, project name, etc.) */
  subtitle?: React.ReactNode;
  /** User name for "Generated by" line */
  generatedBy?: string;
  /** When false, only children are rendered (no branding blocks) */
  showBranding?: boolean;
  children: React.ReactNode;
  className?: string;
}

const PrintReportLayout: React.FC<PrintReportLayoutProps> = ({
  title,
  subtitle,
  generatedBy,
  showBranding = true,
  children,
  className = '',
}) => {
  const { user } = useAuth();

  return (
    <div className={`print-report-surface flex flex-col min-h-0 ${className}`.trim()}>
      {showBranding && <ReportHeader />}
      {(title || subtitle) && (
        <div className="report-title-block text-center mb-4 flex-shrink-0">
          {title && (
            <h2 className="text-xl font-bold text-slate-900 tracking-tight">{title}</h2>
          )}
          {subtitle && (
            <div className="text-sm text-slate-600 mt-1">{subtitle}</div>
          )}
        </div>
      )}
      <div className="flex-1 min-h-0">{children}</div>
      {showBranding && <ReportFooter generatedBy={generatedBy ?? user?.name} />}
    </div>
  );
};

export default PrintReportLayout;
