import type { RegisteredField } from './fieldRegistryTypes.js';

export const ACCOUNTING_LEDGER_MODULE_KEY = 'accounting_ledger';

export const ACCOUNTING_LEDGER_GROUP_DIMENSIONS: Record<string, string> = {
  account_id: 'a.id',
  account_name: 'a.name',
  category_id: 'cat.id',
  category_name: 'cat.name',
  project_id: 'proj.id',
  project_name: 'proj.name',
  contact_id: 'c.id',
  contact_name: 'c.name',
  vendor_id: 'v.id',
  vendor_name: 'v.name',
  txn_type: 't.type',
  txn_month: "date_trunc('month', t.date::timestamp)",
  txn_year: "date_trunc('year', t.date::timestamp)",
};

export function getAccountingLedgerFieldRegistry(): RegisteredField[] {
  return accountingLedgerRegistry;
}

const accountingLedgerRegistry: RegisteredField[] = [
  {
    key: 'txn_id',
    label: 'Transaction ID',
    sourceTable: 'transactions',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 't.id',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'txn_date',
    label: 'Date',
    sourceTable: 'transactions',
    type: 'date',
    filterable: true,
    sortable: true,
    sqlExpr: 't.date',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'txn_type',
    label: 'Type',
    sourceTable: 'transactions',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 't.type',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'amount',
    label: 'Amount',
    sourceTable: 'transactions',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 't.amount',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'description',
    label: 'Description',
    sourceTable: 'transactions',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 't.description',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'reference',
    label: 'Reference',
    sourceTable: 'transactions',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 't.reference',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'account_name',
    label: 'Account',
    sourceTable: 'accounts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'a.name',
    entityGroup: 'Chart of accounts (reference)',
  },
  {
    key: 'category_name',
    label: 'Category',
    sourceTable: 'categories',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'cat.name',
    entityGroup: 'Categories',
  },
  {
    key: 'contact_name',
    label: 'Contact',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'c.name',
    entityGroup: 'Customers',
  },
  {
    key: 'vendor_name',
    label: 'Vendor',
    sourceTable: 'vendors',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'v.name',
    entityGroup: 'Vendors',
  },
  {
    key: 'project_name',
    label: 'Project',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'proj.name',
    entityGroup: 'Projects',
  },
];
