import type { RegisteredField } from './fieldRegistryTypes.js';

/**
 * Canonical module: LAN `project_agreements` (bookings/agreements).
 * Synthetic keys alias legacy naming (`booking_*`) for UX parity with domain language.
 */

export const PROJECT_SELLING_MODULE_KEY = 'project_selling';

export function getProjectSellingFieldRegistry(): RegisteredField[] {
  return projectSellingRegistry;
}

const projectSellingRegistry: RegisteredField[] = [
  // —— Project selling (agreements) ——
  {
    key: 'agreement_id',
    label: 'Agreement ID',
    sourceTable: 'project_agreements',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'pa.id',
    entityGroup: 'Project Selling',
  },
  {
    key: 'booking_no',
    label: 'Booking / agreement no.',
    sourceTable: 'project_agreements',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'pa.agreement_number',
    entityGroup: 'Project Selling',
  },
  {
    key: 'agreement_status',
    label: 'Agreement status',
    sourceTable: 'project_agreements',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'pa.status',
    entityGroup: 'Project Selling',
  },
  {
    key: 'booking_date',
    label: 'Booking / issue date',
    sourceTable: 'project_agreements',
    type: 'date',
    filterable: true,
    sortable: true,
    sqlExpr: 'pa.issue_date',
    entityGroup: 'Project Selling',
  },
  {
    key: 'selling_price',
    label: 'Selling price',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.selling_price',
    entityGroup: 'Project Selling',
  },
  {
    key: 'list_price',
    label: 'List price',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.list_price',
    entityGroup: 'Discounts & pricing',
  },
  {
    key: 'customer_discount',
    label: 'Customer discount',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.customer_discount',
    entityGroup: 'Discounts & pricing',
  },
  {
    key: 'floor_discount',
    label: 'Floor discount',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.floor_discount',
    entityGroup: 'Discounts & pricing',
  },
  {
    key: 'lump_sum_discount',
    label: 'Lump sum discount',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.lump_sum_discount',
    entityGroup: 'Discounts & pricing',
  },
  {
    key: 'misc_discount',
    label: 'Misc. discount',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.misc_discount',
    entityGroup: 'Discounts & pricing',
  },
  {
    key: 'rebate_amount',
    label: 'Rebate / commission rebate',
    sourceTable: 'project_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'pa.rebate_amount',
    entityGroup: 'Commission & rebates',
  },
  {
    key: 'agreement_description',
    label: 'Agreement notes',
    sourceTable: 'project_agreements',
    type: 'string',
    filterable: true,
    sortable: false,
    searchable: true,
    sqlExpr: 'pa.description',
    entityGroup: 'Project Selling',
  },

  // —— Customer / buyer ——
  {
    key: 'customer_id',
    label: 'Customer ID',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'client.id',
    entityGroup: 'Customers',
  },
  {
    key: 'customer_name',
    label: 'Customer name',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'client.name',
    entityGroup: 'Customers',
  },
  {
    key: 'customer_company',
    label: 'Customer company',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'client.company_name',
    entityGroup: 'Customers',
  },
  {
    key: 'customer_type',
    label: 'Customer type',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'client.type',
    entityGroup: 'Customers',
  },

  // —— Project ——
  {
    key: 'project_id',
    label: 'Project ID',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'proj.id',
    entityGroup: 'Projects',
  },
  {
    key: 'project_name',
    label: 'Project name',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'proj.name',
    entityGroup: 'Projects',
  },
  {
    key: 'project_location',
    label: 'Project location',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'proj.location',
    entityGroup: 'Projects',
  },
  {
    key: 'project_type',
    label: 'Project type',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'proj.project_type',
    entityGroup: 'Projects',
  },

  // —— Units (aggregated per agreement) ——
  {
    key: 'unit_numbers',
    label: 'Unit numbers',
    sourceTable: 'units',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'uagg.unit_numbers',
    entityGroup: 'Units',
  },
  {
    key: 'unit_count',
    label: 'Unit count',
    sourceTable: 'units',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'uagg.unit_count',
    entityGroup: 'Units',
  },
  {
    key: 'primary_unit_type',
    label: 'Primary unit type',
    sourceTable: 'units',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'uagg.primary_unit_type',
    entityGroup: 'Units',
  },
  {
    key: 'primary_unit_status',
    label: 'Primary unit status',
    sourceTable: 'units',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'uagg.primary_unit_status',
    entityGroup: 'Units',
  },

  // —— Owner (first linked unit owner) ——
  {
    key: 'owner_id',
    label: 'Owner contact ID',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'ownr.owner_contact_id',
    entityGroup: 'Owners',
  },
  {
    key: 'owner_name',
    label: 'Owner name',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'ownr.owner_contact_name',
    entityGroup: 'Owners',
  },

  // —— Broker (rebate broker contact) ——
  {
    key: 'broker_id',
    label: 'Broker ID',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'broker.id',
    entityGroup: 'Brokers',
  },
  {
    key: 'broker_name',
    label: 'Broker name',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'broker.name',
    entityGroup: 'Brokers',
  },

  // —— Invoices linked to agreement ——
  {
    key: 'invoice_count',
    label: 'Invoice count',
    sourceTable: 'invoices',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'inv_sums.invoice_count',
    entityGroup: 'Installments & invoices',
  },
  {
    key: 'invoice_amount_total',
    label: 'Invoice amount total',
    sourceTable: 'invoices',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'inv_sums.invoice_amount_total',
    entityGroup: 'Installments & invoices',
  },
  {
    key: 'invoice_paid_total',
    label: 'Invoice paid total',
    sourceTable: 'invoices',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'inv_sums.invoice_paid_total',
    entityGroup: 'Payments & receipts',
  },

  // —— Ledger transactions on agreement ——
  {
    key: 'ledger_txn_count',
    label: 'Ledger line count (agreement)',
    sourceTable: 'transactions',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'txn_sums.txn_count',
    entityGroup: 'Accounts & ledger',
  },
  {
    key: 'ledger_txn_amount_sum',
    label: 'Ledger amount sum (agreement)',
    sourceTable: 'transactions',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'txn_sums.txn_amount_net',
    entityGroup: 'Accounts & ledger',
  },

  // —— Sales returns ——
  {
    key: 'return_count',
    label: 'Return / cancellation count',
    sourceTable: 'sales_returns',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'sr_sums.return_count',
    entityGroup: 'Returns & refunds',
  },
  {
    key: 'refunds_total',
    label: 'Refunds total',
    sourceTable: 'sales_returns',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'sr_sums.refunds_total',
    entityGroup: 'Returns & refunds',
  },

  // —— Received assets (possession / barter) ——
  {
    key: 'possession_asset_count',
    label: 'Received asset lines',
    sourceTable: 'project_received_assets',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'asset_sums.assets_received_count',
    entityGroup: 'Possession & assets',
  },
  {
    key: 'possession_asset_value',
    label: 'Received asset value',
    sourceTable: 'project_received_assets',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'asset_sums.assets_received_value',
    entityGroup: 'Possession & assets',
  },

  // —— Installment plan (latest matching lead + project) ——
  {
    key: 'installment_plan_net_value',
    label: 'Installment plan net value (lead match)',
    sourceTable: 'installment_plans',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'ip_one.net_value',
    entityGroup: 'Investor / installment reference',
  },
  {
    key: 'installment_down_payment_pct',
    label: 'Installment down payment %',
    sourceTable: 'installment_plans',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'ip_one.down_payment_percentage',
    entityGroup: 'Investor / installment reference',
  },

  // —— Category labels ——
  {
    key: 'selling_price_category',
    label: 'Selling price category',
    sourceTable: 'categories',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'cat_sell.name',
    entityGroup: 'Categories',
  },
  {
    key: 'rebate_category',
    label: 'Rebate category',
    sourceTable: 'categories',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'cat_rebate.name',
    entityGroup: 'Categories',
  },

  // —— Synthetic time buckets ——
  {
    key: '_bucket_issue_month',
    label: 'Issue month (bucket)',
    type: 'date',
    filterable: false,
    sortable: true,
    sqlExpr: "date_trunc('month', pa.issue_date::timestamp)",
    entityGroup: 'Project Selling',
  },
  {
    key: '_bucket_issue_year',
    label: 'Issue year (bucket)',
    type: 'date',
    filterable: false,
    sortable: true,
    sqlExpr: "date_trunc('year', pa.issue_date::timestamp)",
    entityGroup: 'Project Selling',
  },

  // —— Calculated (evaluated server-side after row fetch when listed in config) ——
  {
    kind: 'calculated',
    key: 'outstanding_vs_invoices',
    label: 'Outstanding (selling price − invoice paid)',
    type: 'number',
    filterable: false,
    sortable: false,
    formula: '{selling_price} - {invoice_paid_total}',
    dependsOn: ['selling_price', 'invoice_paid_total'],
    sqlExpr: 'NULL::numeric',
    entityGroup: 'Payments & receipts',
  },
  {
    kind: 'calculated',
    key: 'discount_total',
    label: 'Discounts total',
    type: 'number',
    filterable: false,
    sortable: false,
    formula:
      '{customer_discount}+{floor_discount}+{lump_sum_discount}+{misc_discount}',
    dependsOn: ['customer_discount', 'floor_discount', 'lump_sum_discount', 'misc_discount'],
    sqlExpr: 'NULL::numeric',
    entityGroup: 'Discounts & pricing',
  },
];
