import type { RegisteredField } from './fieldRegistryTypes.js';

export const PROJECT_CONSTRUCTION_MODULE_KEY = 'project_construction';

export const PROJECT_CONSTRUCTION_GROUP_DIMENSIONS: Record<string, string> = {
  project_id: 'proj.id',
  project_name: 'proj.name',
  vendor_id: 'v.id',
  vendor_name: 'v.name',
  contract_status: 'c.status',
  issue_month: "date_trunc('month', c.start_date::timestamp)",
  issue_year: "date_trunc('year', c.start_date::timestamp)",
};

export function getProjectConstructionFieldRegistry(): RegisteredField[] {
  return projectConstructionRegistry;
}

const projectConstructionRegistry: RegisteredField[] = [
  {
    key: 'contract_id',
    label: 'Contract ID',
    sourceTable: 'contracts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'c.id',
    entityGroup: 'Project construction',
  },
  {
    key: 'contract_number',
    label: 'Contract no.',
    sourceTable: 'contracts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'c.contract_number',
    entityGroup: 'Project construction',
  },
  {
    key: 'contract_name',
    label: 'Contract name',
    sourceTable: 'contracts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'c.name',
    entityGroup: 'Project construction',
  },
  {
    key: 'contract_status',
    label: 'Contract status',
    sourceTable: 'contracts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'c.status',
    entityGroup: 'Project construction',
  },
  {
    key: 'contract_amount',
    label: 'Contract amount',
    sourceTable: 'contracts',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'c.total_amount',
    entityGroup: 'Project construction',
  },
  {
    key: 'start_date',
    label: 'Start date',
    sourceTable: 'contracts',
    type: 'date',
    filterable: true,
    sortable: true,
    sqlExpr: 'c.start_date',
    entityGroup: 'Project construction',
  },
  {
    key: 'end_date',
    label: 'End date',
    sourceTable: 'contracts',
    type: 'date',
    filterable: true,
    sortable: true,
    sqlExpr: 'c.end_date',
    entityGroup: 'Project construction',
  },
  {
    key: 'vendor_id',
    label: 'Vendor ID',
    sourceTable: 'vendors',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'v.id',
    entityGroup: 'Vendors',
  },
  {
    key: 'vendor_name',
    label: 'Vendor name',
    sourceTable: 'vendors',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'v.name',
    entityGroup: 'Vendors',
  },
  {
    key: 'vendor_company',
    label: 'Vendor company',
    sourceTable: 'vendors',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'v.company_name',
    entityGroup: 'Vendors',
  },
  {
    key: 'project_id',
    label: 'Project ID',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'proj.id',
    entityGroup: 'Projects',
  },
  {
    key: 'project_name',
    label: 'Project name',
    sourceTable: 'projects',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'proj.name',
    entityGroup: 'Projects',
  },
  {
    key: 'billed_total',
    label: 'Billed total',
    sourceTable: 'bills',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'bill_sums.billed',
    entityGroup: 'Expenses',
  },
  {
    key: 'paid_total',
    label: 'Paid total',
    sourceTable: 'bills',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'bill_sums.paid',
    entityGroup: 'Expenses',
  },
  {
    key: 'outstanding',
    label: 'Outstanding',
    sourceTable: 'bills',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'GREATEST(COALESCE(bill_sums.billed, 0) - COALESCE(bill_sums.paid, 0), 0)',
    entityGroup: 'Expenses',
  },
  {
    key: 'overdue_amount',
    label: 'Overdue amount',
    sourceTable: 'bills',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'COALESCE(od.overdue_amount, 0)',
    entityGroup: 'Expenses',
  },
  {
    key: 'bill_count',
    label: 'Bill count',
    sourceTable: 'bills',
    type: 'number',
    filterable: false,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'bill_sums.bill_count',
    entityGroup: 'Expenses',
  },
];
