import type { RegisteredField } from './fieldRegistryTypes.js';

export const RENTAL_AGREEMENTS_MODULE_KEY = 'rental_agreements';

export const RENTAL_AGREEMENTS_GROUP_DIMENSIONS: Record<string, string> = {
  property_id: 'prop.id',
  property_name: 'prop.name',
  building_id: 'bld.id',
  building_name: 'bld.name',
  tenant_id: 'tenant.id',
  tenant_name: 'tenant.name',
  owner_id: 'owner.id',
  owner_name: 'owner.name',
  broker_id: 'broker.id',
  broker_name: 'broker.name',
  status: 'ra.status',
  start_month: "date_trunc('month', ra.start_date::timestamp)",
  start_year: "date_trunc('year', ra.start_date::timestamp)",
  end_month: "date_trunc('month', ra.end_date::timestamp)",
};

export function getRentalAgreementsFieldRegistry(): RegisteredField[] {
  return rentalAgreementsRegistry;
}

const rentalAgreementsRegistry: RegisteredField[] = [
  {
    key: 'agreement_id',
    label: 'Agreement ID',
    sourceTable: 'rental_agreements',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'ra.id',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'agreement_number',
    label: 'Agreement no.',
    sourceTable: 'rental_agreements',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'ra.agreement_number',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'status',
    label: 'Status',
    sourceTable: 'rental_agreements',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'ra.status',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'start_date',
    label: 'Start date',
    sourceTable: 'rental_agreements',
    type: 'date',
    filterable: true,
    sortable: true,
    sqlExpr: 'ra.start_date',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'end_date',
    label: 'End date',
    sourceTable: 'rental_agreements',
    type: 'date',
    filterable: true,
    sortable: true,
    sqlExpr: 'ra.end_date',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'monthly_rent',
    label: 'Monthly rent',
    sourceTable: 'rental_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'ra.monthly_rent',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'security_deposit',
    label: 'Security deposit',
    sourceTable: 'rental_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'ra.security_deposit',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'broker_fee',
    label: 'Broker fee',
    sourceTable: 'rental_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    aggregatable: true,
    sqlExpr: 'ra.broker_fee',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'rent_due_date',
    label: 'Rent due day',
    sourceTable: 'rental_agreements',
    type: 'number',
    filterable: true,
    sortable: true,
    sqlExpr: 'ra.rent_due_date',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'description',
    label: 'Description',
    sourceTable: 'rental_agreements',
    type: 'string',
    filterable: true,
    searchable: true,
    sqlExpr: 'ra.description',
    entityGroup: 'Rental agreements',
  },
  {
    key: 'tenant_id',
    label: 'Tenant ID',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'tenant.id',
    entityGroup: 'Rental tenants',
  },
  {
    key: 'tenant_name',
    label: 'Tenant name',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'tenant.name',
    entityGroup: 'Rental tenants',
  },
  {
    key: 'property_id',
    label: 'Property ID',
    sourceTable: 'properties',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'prop.id',
    entityGroup: 'Rental properties',
  },
  {
    key: 'property_name',
    label: 'Property name',
    sourceTable: 'properties',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'prop.name',
    entityGroup: 'Rental properties',
  },
  {
    key: 'building_id',
    label: 'Building ID',
    sourceTable: 'buildings',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'bld.id',
    entityGroup: 'Rental properties',
  },
  {
    key: 'building_name',
    label: 'Building name',
    sourceTable: 'buildings',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'bld.name',
    entityGroup: 'Rental properties',
  },
  {
    key: 'owner_id',
    label: 'Owner ID',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'owner.id',
    entityGroup: 'Owners',
  },
  {
    key: 'owner_name',
    label: 'Owner name',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'owner.name',
    entityGroup: 'Owners',
  },
  {
    key: 'broker_id',
    label: 'Broker ID',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    sqlExpr: 'broker.id',
    entityGroup: 'Brokers',
  },
  {
    key: 'broker_name',
    label: 'Broker name',
    sourceTable: 'contacts',
    type: 'string',
    filterable: true,
    sortable: true,
    searchable: true,
    sqlExpr: 'broker.name',
    entityGroup: 'Brokers',
  },
];
