import {
  ArrowDownCircle,
  ArrowUpCircle,
  Banknote,
  Building2,
  CalendarCheck,
  FileText,
  HandCoins,
  Home,
  Landmark,
  Receipt,
  TrendingUp,
  UserPlus,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

/** Lucide icons for executive dashboard KPI ids (Phase 2 main dashboard). */
export const DASHBOARD_METRIC_ICONS: Record<string, LucideIcon> = {
  totalCashBalance: Wallet,
  bankBalance: Landmark,
  accountsReceivable: ArrowDownCircle,
  accountsPayable: FileText,
  netIncome: TrendingUp,
  revenue: ArrowDownCircle,
  expenses: ArrowUpCircle,
  operatingCashFlow: HandCoins,
  activeProjects: Building2,
  unitsAvailable: Home,
  unitsSold: Home,
  collectionRate: Receipt,
  outstandingReceivables: Banknote,
  activeRentalProperties: Building2,
  occupancyRate: Users,
  securityDepositsHeld: Wallet,
  newCustomers: UserPlus,
  newVendors: UserPlus,
  newAgreements: CalendarCheck,
  newBookings: CalendarCheck,
  newReceipts: Receipt,
  newPayments: Banknote,
};
