
-- Disable RLS on Shop tables temporarily for debugging
ALTER TABLE shop_branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_terminals DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_warehouses DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_products DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_loyalty_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_inventory_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE shop_policies DISABLE ROW LEVEL SECURITY;

-- Disable RLS on core tables joined by Shop modules (Fixes "sync" visibility issues)
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;

-- Disable RLS on other main entities to ensure system-wide visibility
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE buildings DISABLE ROW LEVEL SECURITY;
ALTER TABLE properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE units DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE bills DISABLE ROW LEVEL SECURITY;

